### ISSUE TITLE
Remove target directory from git

### ISSUE THREAD

**Issue by MontealegreLuis** [TeamVigor/Fitify#23]
Please remove the `target` directory from git

```
git rm -r --cached target
```

Commit, and PR as usual

Thank you!

**Comment by Docalvi** [comment]
fixed the issue

**Comment by MontealegreLuis** [comment]
I still see it there... 

https://github.com/TeamVigor/Fitify/tree/master/target/classes

Have you merged with master?
